name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to PythonAnywhere
        env:
          PA_TOKEN: ${{ secrets.PYTHONANYWHERE_TOKEN }}
        run: |
          curl -X POST \
          --header "Authorization: Token ${PA_TOKEN}" \
          https://www.pythonanywhere.com/api/v0/user/nassermendes/webapps/nassermendes.pythonanywhere.com/reload/
